### ISSUE TITLE
 Function Execution

### ISSUE THREAD

**Issue by Amira-Fareed** [Abuelseaoud/g22#16]
one function : CMatrix functionExe(int i,CMatrix &m,int r=0,int c=0) 
calculate function and return the result matrix 
functions like{ "sinh",	"cosh",	"tanh","coth","sech","csch",
	                            "sin","cos","tan","cot","sec","csc",	
                                "asin",	"acos","atan","acot","asec","acsc",	
                                "sqrt","rand","eye","zeros","ones","log10","log","exp"};

**Comment by Abuelseaoud** [comment]
done ant tested
