### ISSUE TITLE
Flexible matrix parser

### ISSUE THREAD

**Issue by Amira-Fareed** [Abuelseaoud/g22#5]
Accept matrix in matrix, expressions and variables

**Comment by Abuelseaoud** [comment]
3 ways of initialize  the matrix:
only numbers separated by spaces and ;     (done in phase 1 )
new edits :
Concatenation of matrices
Concatenation of matrices+numbers
zeros()&rand()&eye()&ones()
for more info :https://www.mathworks.com/help/matlab/math/creating-and-concatenating-matrices.html

**Comment by Amira-Fareed** [comment]
- [x] remove duplicated spaces

- [x] Trim spaces before and after operations

- [x] Subtract the expression 

- [x] Replace the expression with the result at the same position 

- [x] Replace the variables with matrices 

- [x] Concatenate 

- [x] modify the string to match the standard format
